# Generated by Django 5.1.5 on 2025-02-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='original_link',
            field=models.URLField(max_length=500),
        ),
    ]
