# Generated by Django 5.1.5 on 2025-02-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_shortenedurl_original_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='original_link_en',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shortenedurl',
            name='original_link_ru',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shortenedurl',
            name='original_link_uz',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
