# Generated by Django 5.1.5 on 2025-02-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_shortenedurl_original_link_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='short_link',
            field=models.CharField(default='http://127.0.0.1:8000/ru/api/<function generate_short_link at 0x000001B5F0C1E480>', max_length=10, unique=True),
        ),
    ]
