# Generated by Django 5.1.5 on 2025-02-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_shortenedurl_short_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='short_link',
            field=models.CharField(default='http://127.0.0.1:8000/ru/api/<function generate_short_link at 0x000001DB7298E480>', max_length=100, unique=True),
        ),
    ]
