# Generated by Django 5.1.5 on 2025-02-10 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_shortenedurl_short_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortenedurl',
            name='original_link_en',
        ),
        migrations.RemoveField(
            model_name='shortenedurl',
            name='original_link_ru',
        ),
        migrations.RemoveField(
            model_name='shortenedurl',
            name='original_link_uz',
        ),
    ]
