# Generated by Django 5.1.5 on 2025-02-20 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_shortenedurl_original_link_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='shortened_urls', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
