# Generated by Django 5.1.5 on 2025-03-02 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_shortenedurl_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortenedurl',
            name='clicks',
        ),
    ]
