# Generated by Django 5.1.5 on 2025-03-03 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_baseshortenedurl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseShortenedURL',
        ),
    ]
