# Generated by Django 5.1.5 on 2025-03-14 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_delete_baseshortenedurl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortenedurl',
            options={'ordering': ['-created_at']},
        ),
    ]
