# Generated by Django 5.1.5 on 2025-03-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_alter_shortenedurl_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
